lab06/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tienda/', include('tienda.urls')),
]

if settings.DEBUG: 
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

tienda/urls.py
from django.urls import path
from . import views

app_name = 'tienda'

urlpatterns = [
    path('',views.index,name='index'),
    path('producto/<int:producto_id>/',views.producto,name='productos'),
    path('categoria/<int:categoria_id>/',views.categoria,name='categorias'),
]

tienda/models.py
from django.db import models

class Categoria(models.Model):
    nombre = models.CharField(max_length=100)
    pub_date = models.DateTimeField('Fecha de registro')
    
    def __str__(self):
        return self.nombre
    
class Producto(models.Model):
    nombre = models.CharField(max_length=100)
    precio = models.DecimalField(max_digits=10,decimal_places=2)
    detalle = models.TextField(max_length=1000, null=True)
    categoria = models.ForeignKey(Categoria,on_delete=models.CASCADE)
    pub_date = models.DateTimeField('Fecha de registro')
    stock = models.IntegerField(default=0)
    imagen = models.ImageField(upload_to="products",null=True)
    
    def __str__(self):
        return self.nombre

tienda/views.py
from django.shortcuts import get_object_or_404, render
from .models import Producto, Categoria

def index(request):
    product_list = Producto.objects.all()
    context = {
        'product_list': product_list
    }
    return render(request, 'index.html', context)

def producto(request, producto_id):
    producto = get_object_or_404(Producto, pk=producto_id)
    return render(request, 'producto.html', {'producto': producto})

def categoria(request, categoria_id):
    categoria = get_object_or_404(Categoria, pk=categoria_id)
    productos_list = Producto.objects.filter(categoria=categoria)
    cantidad_productos = productos_list.count()  
    context = {
        'categoria': categoria,
        'productos_list': productos_list,
        'cantidad_productos': cantidad_productos,  
    }
    return render(request, 'categoria.html', context)

tienda/templates/categoria.html
{% extends "layout.html" %}
{% block content %}
<!-- Start Breadcrumbs -->
<div class="breadcrumbs">
  <div class="container">
      <div class="row align-items-center">
          <div class="col-lg-6 col-md-6 col-12">
              <div class="breadcrumbs-content">
                  <h1 class="page-title">Productos de tienda</h1>
              </div>
          </div>
      </div>
  </div>
</div>
<!-- End Breadcrumbs -->

<!-- Start Product Grids -->
<section class="product-grids section">
  <div class="container">
      <div class="row">
          <div class="col-lg-3 col-12">
              <!-- Start Product Sidebar -->
              <div class="product-sidebar">
                  <!-- Start Single Widget -->
                  <div class="single-widget search">
                      <h3 class="fs-3 mb-3">Buscar</h3>
                      <form action="#" class="mb-3">
                          <div class="input-group rounded">
                              <input type="search" class="form-control rounded" placeholder="Search" aria-label="Search" aria-describedby="search-addon" />
                              <button type="button" class="btn btn-warning" data-mdb-ripple-init>
                                  <i class="fas fa-search text-white" ></i>
                                </button>
                            </div>
                      </form>
                  </div>
                  <!-- End Single Widget -->
                  <!-- Start Single Widget -->
                  <div class="single-widget">
                      <h3 class="fs-3 mb-3">Categorias</h3>
                      <ul class="list">
                          {% for cat in categoria_list %}
                              <li>
                                  <a class="text-decoration-none text-warning" href="{% url 'tienda:categorias' cat.id %}">{{cat.nombre}} </a><span>({{ cat.producto_set.count }})</span>
                              </li>
                          {% endfor %}
                      </ul>
                  </div>
                  <!-- End Single Widget -->
              </div>
              <!-- End Product Sidebar -->
          </div>
          <div class="col-lg-9 col-12">
              <div class="product-grids-head">
                  <div class="product-grid-topbar">
                      <div class="row align-items-center">
                          <div class="col-lg-8 ">
                              <div class="nav " id="nav-tab" role="tablist">
                                  <div class="btn-group" role="group" aria-label="Button group with nested dropdown">
                                      <button class="btn btn-outline-warning active" id="grid-3-columns" data-bs-toggle="tab"
                                          data-bs-target="#nav-grid" type="button" role="tab"
                                          aria-controls="nav-grid" aria-selected="true">
                                          <i class="fa-solid fa-table-columns text-white"></i>
                                      </button>
                                      <button class="btn btn-outline-warning" id="grid-1-column" data-bs-toggle="tab"
                                          data-bs-target="#nav-list" type="button" role="tab"
                                          aria-controls="nav-list" aria-selected="false">
                                          <i class="fa-solid fa-list"></i>
                                      </button>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
                  <div class="tab-content" id="nav-tabContent">
                      <div class="tab-pane fade show active" id="nav-grid" role="tabpanel"
                          aria-labelledby="nav-grid-tab">
                          <div class="row row-cols-3" id="product-grid">
                                  <!-- Start Single Product -->
                                  {% for prod in productos_list %}
                                  <div class="col">
                                  <div class="single-product">
                                      <div class="product-image">
                                          <a href="../../producto/{{prod.id}}"><img class="card-img-top"src="{{ prod.imagen.url }}" alt=""></a>
                                          <div class="button btn-warning">
                                              <a href="product-details.html" class="btn"><i class="fa-solid fa-cart-shopping"></i>Agregar</a>
                                          </div>
                                      </div>
                                      <div class="product-info">
                                          <span class="category">{{prod.categoria.nombre}}</span>
                                          <h4 class="title">
                                              <a href="product-grids.html">{{prod.nombre}}</a>
                                          </h4>
                                          <div class="price">
                                              <span>S/. {{prod.precio}}</span>
                                          </div>
                                      </div>
                                  </div>
                              </div>
                                  {% endfor %}
                                  <!-- End Single Product -->
                          </div>

                      </div>
                  </div>
              </div>
          </div>
      </div>
  </div>
</section>
<!-- End Product Grids -->

{% endblock %}

tienda/templates/index.html
{% extends "layout.html" %}
{% block content %}
<!-- Start Breadcrumbs -->
<div class="breadcrumbs">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-6 col-md-6 col-12">
                <div class="breadcrumbs-content">
                    <h1 class="page-title">Productos de tienda</h1>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End Breadcrumbs -->

 <!-- Start Product Grids -->
 <section class="product-grids section">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-12">
                <!-- Start Product Sidebar -->
                <div class="product-sidebar">
                    <!-- Start Single Widget -->
                    <div class="single-widget search">
                        <h3 class="fs-3 mb-3">Buscar</h3>
                        <form action="#" class="mb-3">
                            <div class="input-group rounded">
                                <input type="search" class="form-control rounded" placeholder="Search" aria-label="Search" aria-describedby="search-addon" />
                                <button type="button" class="btn btn-warning" data-mdb-ripple-init>
                                    <i class="fas fa-search text-white" ></i>
                                  </button>
                              </div>
                        </form>
                    </div>
                    <!-- End Single Widget -->
                    <!-- Start Single Widget -->
                    <div class="single-widget">
                        <h3 class="fs-3 mb-3">Categorias</h3>
                        <ul class="list">
                            {% for cat in categoria_list %}
                                <li>
                                    <a class="text-decoration-none text-warning" href="{% url 'tienda:categorias' cat.id %}">{{cat.nombre}} </a><span>({{ cat.producto_set.count }})</span>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                    <!-- End Single Widget -->
                </div>
                <!-- End Product Sidebar -->
            </div>
            <div class="col-lg-9 col-12">
                <div class="product-grids-head">
                    <div class="product-grid-topbar">
                        <div class="row align-items-center">
                            <div class="col-lg-8 ">
                                <div class="nav " id="nav-tab" role="tablist">
                                    <div class="btn-group" role="group" aria-label="Button group with nested dropdown">
                                        <button class="btn btn-outline-warning active" id="grid-3-columns" data-bs-toggle="tab"
                                            data-bs-target="#nav-grid" type="button" role="tab"
                                            aria-controls="nav-grid" aria-selected="true">
                                            <i class="fa-solid fa-table-columns text-white"></i>
                                        </button>
                                        <button class="btn btn-outline-warning" id="grid-1-column" data-bs-toggle="tab"
                                            data-bs-target="#nav-list" type="button" role="tab"
                                            aria-controls="nav-list" aria-selected="false">
                                            <i class="fa-solid fa-list"></i>
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="tab-content" id="nav-tabContent">
                        <div class="tab-pane fade show active" id="nav-grid" role="tabpanel"
                            aria-labelledby="nav-grid-tab">
                            <div class="row row-cols-3" id="product-grid">
                                    <!-- Start Single Product -->
                                    {% for prod in product_list %}
                                    <div class="col">
                                    <div class="single-product">
                                        <div class="product-image">
                                            <a href="producto/{{prod.id}}"><img class="card-img-top"src="{{ prod.imagen.url }}" alt=""></a>
                                            <div class="button btn-warning">
                                                <a href="product-details.html" class="btn"><i class="fa-solid fa-cart-shopping"></i>Agregar</a>
                                            </div>
                                        </div>
                                        <div class="product-info">
                                            <span class="category">{{prod.categoria.nombre}}</span>
                                            <h4 class="title">
                                                <a href="product-grids.html">{{prod.nombre}}</a>
                                            </h4>
                                            <div class="price">
                                                <span>S/. {{prod.precio}}</span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                    {% endfor %}
                                    <!-- End Single Product -->
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- End Product Grids -->
{% endblock %}

tienda/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html class="no-js" lang="zxx">

<head>
    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <title>StoreLau</title>
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!-- ========================= CSS here ========================= -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}" />
    <link rel="stylesheet" href="{% static 'css/LineIcons.3.0.css'%}" />
    <link rel="stylesheet" href="{% static 'css/tiny-slider.css'%}" />
    <link rel="stylesheet" href="{% static 'css/glightbox.min.css'%}" />
    <link rel="stylesheet" href="{% static 'css/main.css'%}" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    
</head>

<body>
    <!-- Start Header Area -->
    <header class="header navbar-area">
        <!-- Start Topbar -->
        <div class="topbar bg-warning">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-4 col-md-4 col-12">
                        <div class="top-left">
                            <a class="text-white text-decoration-none fs-4 fw-bold" href="{% url 'tienda:index' %}">StoreHC</a>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-4 col-12">
                        <div class="top-middle">
                            <ul class="useful-links">
                                <li><a class="text-decoration-none text-white"  href="{% url 'tienda:index' %}">Inicio</a></li>
                                <li><a class="text-decoration-none text-white" href="{% url 'tienda:index' %}">Nosotros</a></li>
                                <li><a class="text-decoration-none text-white" href="{% url 'tienda:index' %}">Contactanos</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-4 col-12">
                        <div class="top-end">
                            <ul class="user-login">
                                <li>
                                    <a class="text-decoration-none text-white" href="login.html">Iniciar sesión</a>
                                </li>
                                <li>
                                    <a class="text-decoration-none text-white" href="register.html">Registrarse</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End Topbar -->
        <!-- Start Header Middle -->
        <div class="header-middle">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-3 col-md-3 col-7">
                        <!-- Start Header Logo -->
                        <a class="navbar-brand" href="{% url 'tienda:index' %}">
                            <img src="{% static 'images/logo.png' %}" style="width: 17%" alt="Logo">
                        </a>
                        <!-- End Header Logo -->
                    </div>
                    <div class="col-lg-5 col-md-7 d-xs-none">
                        <!-- Start Main Menu Search -->
                        <div class="main-menu-search">
                            <!-- navbar search start -->
                            <div class="navbar-search search-style-5">
                                <div class="search-input">
                                    <input type="text" placeholder="Buscar">
                                </div>
                                <div class="search-btn">
                                    <button class="bg-warning"><i class="fa-solid fa-magnifying-glass"></i></button>
                                </div>
                            </div>
                            <!-- navbar search Ends -->
                        </div>
                        <!-- End Main Menu Search -->
                    </div>
                    <div class="col-lg-4 col-md-2 col-5">
                        <div class="middle-right-area">
                            <div class="nav-hotline">
                               
                            </div>
                            <div class="navbar-cart justify-content-end">
                                <div class="cart-items">
                                    <a href="javascript:void(0)" class="main-btn">
                                        <i class="fa-solid fa-cart-shopping"></i>
                                        <span class="total-items">2</span>
                                    </a>
                                    <!-- Shopping Item -->
                                    <div class="shopping-item">
                                        <div class="dropdown-cart-header">
                                            <span>2 Items</span>
                                            <a href="cart.html">View Cart</a>
                                        </div>
                                        <ul class="shopping-list">
                                            <li>
                                                <a href="javascript:void(0)" class="remove" title="Remove this item"><i
                                                        class="lni lni-close"></i></a>
                                                <div class="cart-img-head">
                                                    <a class="cart-img" href="product-details.html"><img
                                                            src="assets/images/header/cart-items/item1.jpg" alt="#"></a>
                                                </div>

                                                <div class="content">
                                                    <h4><a href="product-details.html">
                                                            Apple Watch Series 6</a></h4>
                                                    <p class="quantity">1x - <span class="amount">$99.00</span></p>
                                                </div>
                                            </li>
                                            <li>
                                                <a href="javascript:void(0)" class="remove" title="Remove this item"><i
                                                        class="lni lni-close"></i></a>
                                                <div class="cart-img-head">
                                                    <a class="cart-img" href="product-details.html"><img
                                                            src="assets/images/header/cart-items/item2.jpg" alt="#"></a>
                                                </div>
                                                <div class="content">
                                                    <h4><a href="product-details.html">Wi-Fi Smart Camera</a></h4>
                                                    <p class="quantity">1x - <span class="amount">$35.00</span></p>
                                                </div>
                                            </li>
                                        </ul>
                                        <div class="bottom">
                                            <div class="total">
                                                <span>Total</span>
                                                <span class="total-amount">$134.00</span>
                                            </div>
                                            <div class="button">
                                                <a href="checkout.html" class="btn animate">Checkout</a>
                                            </div>
                                        </div>
                                    </div>
                                    <!--/ End Shopping Item -->
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End Header Middle -->
        <!-- Start Header Bottom -->
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-8 col-md-6 col-12">
                    <div class="nav-inner">
                        <!-- Start Mega Category Menu -->
                        <div class="mega-category-menu">
                            <span class="cat-button"><i class="fa-solid fa-bars"></i>Categorias</span>
                            <ul class="sub-category">
                                {% for cat in categoria_list %}
                                    <li><a href="{% url 'tienda:categorias' cat.id %}">{{cat.nombre}}</a></li>
                                {% endfor %}
                            </ul>
                        </div>
                        <!-- End Mega Category Menu -->
                        <!-- Start Navbar -->
                        <nav class="navbar navbar-expand-lg">
                            <button class="navbar-toggler mobile-menu-btn" type="button" data-bs-toggle="collapse"
                                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                                aria-expanded="false" aria-label="Toggle navigation">
                                <span class="toggler-icon"></span>
                                <span class="toggler-icon"></span>
                                <span class="toggler-icon"></span>
                            </button>
                            <div class="collapse navbar-collapse sub-menu-bar" id="navbarSupportedContent">
                                <ul id="nav" class="navbar-nav ms-auto p-4">
                                    
                                </ul>
                            </div> <!-- navbar collapse -->
                        </nav>
                        <!-- End Navbar -->
                    </div>
                </div>
                <div class="col-lg-4 col-md-6 col-12 mt-2">
                    <!-- Start Nav Social -->
                    <div class="nav-social">
                        <h5 class="title">Siguenos</h5>
                        <ul>
                            <li>
                                <a href="javascript:void(0)"><i class="fa-brands fa-facebook-f"></i></a>
                            </li>
                            <li>
                                <a href="javascript:void(0)"><i class="fa-brands fa-twitter"></i></a>
                            </li>
                            <li>
                                <a href="javascript:void(0)"><i class="fa-brands fa-instagram"></i></a>
                            </li>
                        </ul>
                    </div>
                    <!-- End Nav Social -->
                </div>
            </div>
        </div>
        <!-- Start Header Bottom -->
    </header>
    <!-- End Header Area -->
    <!-- Start Breadcrumbs -->
    
    <!-- Block Content -->
    {% block content %} {% endblock %}
    <!-- /Block Content -->

    <!-- End Breadcrumbs -->


    <!-- ========================= scroll-top ========================= -->
    <a href="#" class="scroll-top">
        <i class="lni lni-chevron-up"></i>
    </a>

    <!-- ========================= JS here ========================= -->
    <script src="{% static 'vendor/bootstrap/js/js/bootstrap.min.js'%}"></script>
    <script src="{% static 'vendor/bootstrap/js/tiny-slider.js'%}"></script>
    <script src="{% static 'vendor/bootstrap/js/glightbox.min.js'%}"></script>
    <script src="{% static 'vendor/bootstrap/js/main.js' %}"></script>
</body>

</html>

tienda/templates/producto.html
{% extends "layout.html" %}
{% block content %}
 <!-- Start Breadcrumbs -->
 <div class="breadcrumbs">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-6 col-md-6 col-12">
                <div class="breadcrumbs-content">
                    <h1 class="page-title">Solo Producto</h1>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End Breadcrumbs -->

<!-- Start Item Details -->
<section class="item-details section">
    <div class="container">
        <div class="top-area">
            <div class="row align-items-center">
                <div class="col-lg-6 col-md-12 col-12">
                    <div class="product-images">
                        <main id="gallery">
                            <div class="main-img">
                                <img src="{{producto.imagen.url}}" id="current" alt="#">
                            </div>
                        </main>
                    </div>
                </div>
                <div class="col-lg-6 col-md-12 col-12">
                    <div class="product-info">
                        <h2 class="title">{{producto.nombre}}</h2>
                        <p class="category">{{producto.categoria.nombre}}</p>
                        <h3 class="price">S/. {{producto.precio}}</h3>
                        <p class="info-text">{{producto.detalle}}</p>
                        
                        <div class="bottom-content">
                            <div class="row align-items-end">
                                <div class="col-lg-4 col-md-4 col-12">
                                    <div class="button cart-button">
                                        <button class="btn" style="width: 100%;">Agregar al carro</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- End Item Details -->


{% endblock %}